Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - './spec/spec_helper.rb'
    - './test/*'
    - './spec/rails_helper.rb'
    - './node_modules/**/*'

  TargetRubyVersion: 2.6.3
